services:
  redis:
    container_name: cache
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data

  mysql:
    container_name: database
    image: mysql
    restart: always
    command: mysqld --bind-address=0.0.0.0 --skip-networking=0 --default-authentication-plugin=caching_sha2_password
    env_file:
      - .env.docker
    ports:
      - 3306:3306
    volumes:
      - G:/MySQL-Data/MySQL Server 8.0/Docker-Data:/var/lib/mysql:rw

volumes:
  redis:
    driver: local
